[package]
name = "noise-hoihoi-app"
description = "NoiseHoiHoi desktop application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[build-dependencies]
winresource = "0.1.31"

[target.'cfg(any(windows, target_os = "linux"))'.dependencies]
gpui-kit.workspace = true
env_logger = "0.11"
image = { version = "0.25", default-features = false, features = ["png"] }
noise-hoihoi-engine = { path = "../noise-hoihoi-engine" }
noise-hoihoi-session = { path = "../noise-hoihoi-session" }
noise-hoihoi-platform = { path = "../noise-hoihoi-platform" }

[lints]
workspace = true
